// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Xb-ggohuQplhI41heIk0ruhEak_131Q',
    appId: '1:953341380653:web:6266563fe8458e3a2690a4',
    messagingSenderId: '953341380653',
    projectId: 'prime-leads-latest',
    authDomain: 'prime-leads-latest.firebaseapp.com',
    storageBucket: 'prime-leads-latest.firebasestorage.app',
    measurementId: 'G-3CBDKQHDMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpfR2Evft2KkHjrqNnaxWvfxxiqa6-Ww',
    appId: '1:953341380653:android:a6b7461961526ffa2690a4',
    messagingSenderId: '953341380653',
    projectId: 'prime-leads-latest',
    storageBucket: 'prime-leads-latest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6gx1WMgsXu3CG_O-5hLj5JUMLMgiooo',
    appId: '1:953341380653:ios:ef288bd82332b63b2690a4',
    messagingSenderId: '953341380653',
    projectId: 'prime-leads-latest',
    storageBucket: 'prime-leads-latest.firebasestorage.app',
    iosBundleId: 'com.quick.primeleads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6gx1WMgsXu3CG_O-5hLj5JUMLMgiooo',
    appId: '1:953341380653:ios:ee4b2847a173927a2690a4',
    messagingSenderId: '953341380653',
    projectId: 'prime-leads-latest',
    storageBucket: 'prime-leads-latest.firebasestorage.app',
    iosBundleId: 'com.quick.primeLeads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Xb-ggohuQplhI41heIk0ruhEak_131Q',
    appId: '1:953341380653:web:cfa52edd107d168d2690a4',
    messagingSenderId: '953341380653',
    projectId: 'prime-leads-latest',
    authDomain: 'prime-leads-latest.firebaseapp.com',
    storageBucket: 'prime-leads-latest.firebasestorage.app',
    measurementId: 'G-8XG0MKVRHF',
  );

}