// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAm_hELn8AMyG81oQxympbZX11pyYr92o',
    appId: '1:516458645301:web:1d96d2b02fd4beafe82e7c',
    messagingSenderId: '516458645301',
    projectId: 'prime-leads-f3054',
    authDomain: 'prime-leads-f3054.firebaseapp.com',
    storageBucket: 'prime-leads-f3054.firebasestorage.app',
    measurementId: 'G-9GKRBM3RSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWY7Pbt3XyKDRhIcIq49qgsY0BeVtj398',
    appId: '1:516458645301:android:12299acc985fe341e82e7c',
    messagingSenderId: '516458645301',
    projectId: 'prime-leads-f3054',
    storageBucket: 'prime-leads-f3054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCzVh-e08lhFuhyArTj6-XmV8bnW_nPo',
    appId: '1:516458645301:ios:7b8d5a8872f90551e82e7c',
    messagingSenderId: '516458645301',
    projectId: 'prime-leads-f3054',
    storageBucket: 'prime-leads-f3054.firebasestorage.app',
    iosBundleId: 'com.quick.primeLeads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCzVh-e08lhFuhyArTj6-XmV8bnW_nPo',
    appId: '1:516458645301:ios:7b8d5a8872f90551e82e7c',
    messagingSenderId: '516458645301',
    projectId: 'prime-leads-f3054',
    storageBucket: 'prime-leads-f3054.firebasestorage.app',
    iosBundleId: 'com.quick.primeLeads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAm_hELn8AMyG81oQxympbZX11pyYr92o',
    appId: '1:516458645301:web:15c67d3d9547b9cee82e7c',
    messagingSenderId: '516458645301',
    projectId: 'prime-leads-f3054',
    authDomain: 'prime-leads-f3054.firebaseapp.com',
    storageBucket: 'prime-leads-f3054.firebasestorage.app',
    measurementId: 'G-KLSNJY7J5K',
  );
}
